# Generated by Django 6.0 on 2025-12-16 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(unique=True)),
                ('email', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=2000)),
                ('pin_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude in decimal degrees', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude in decimal degrees', max_digits=9)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('altitude_meters', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.user')),
            ],
        ),
    ]
